# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Build and Deploy Spring Boot App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up JDK 17 for Java
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '21'

    # Step 3: Cache Maven dependencies to speed up build
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    # Step 4: Build the Spring Boot application
    - name: Build with Maven
      run: mvn clean package

    # Step 5: Run the Spring Boot application
    - name: Run Spring Boot Application
      run: |
        java -jar target/*.jar &
        echo "Spring Boot application is starting..."

    # Step 6: Wait for Spring Boot to start (Adjust the time as needed)
    - name: Wait for Spring Boot to start
      run: sleep 10

    # Step 7: Test the application is running and accessible
    - name: Test Application
      run: curl --fail http://localhost:8080 || exit 1

    # Step 8: Expose the application URL via ngrok (optional step)
    - name: Expose Application using ngrok
      uses: actions/checkout@v3
      run: |
        curl https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -o ngrok.zip
        unzip ngrok.zip
        ./ngrok http 8080 &
        echo "ngrok is starting..."
        sleep 10
        curl http://127.0.0.1:4040/api/tunnels
